# Generated by Django 3.0.1 on 2020-04-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributer', '0001_initial'),
    ]

