# Generated by Django 3.0.1 on 2020-04-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributer', '0002_pricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_type', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
