# Generated by Django 3.0.1 on 2020-04-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distributer', '0003_pricemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockdetails',
            name='s_date',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
