# Generated by Django 3.0.1 on 2020-04-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='Tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
