# Generated by Django 3.0.1 on 2020-04-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer', '0002_auto_20200420_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='datetime',
            field=models.CharField(max_length=30),
        ),
    ]
