# Generated by Django 3.0.1 on 2020-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cust_no', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('Cy_type', models.CharField(max_length=10)),
                ('date_conn', models.DateField()),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
