# Generated by Django 3.0.1 on 2020-04-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateTimeField()),
                ('stock_comm', models.IntegerField()),
                ('stock_dom', models.IntegerField()),
                ('defective_comm', models.IntegerField()),
                ('defective_dom', models.IntegerField()),
                ('current_stock_comm', models.IntegerField()),
                ('current_stock_dom', models.IntegerField()),
            ],
        ),
    ]
