# Generated by Django 3.0.1 on 2020-04-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_stockdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.IntegerField()),
                ('cust_no', models.IntegerField()),
                ('cy_type', models.CharField(max_length=10)),
                ('bk_date', models.DateTimeField()),
                ('del_date', models.DateTimeField()),
                ('amt', models.FloatField()),
            ],
        ),
    ]
