# Generated by Django 3.0.1 on 2020-04-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_billingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('cy_type', models.CharField(max_length=10)),
                ('cust_name', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
