# Generated by Django 3.0.1 on 2020-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_transactionmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='billingmodel',
            name='cust_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
